<a href="https://colab.research.google.com/github/WestianPKl/data-science/blob/main/01_wprowadzenie/02_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [6]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [7]:
#Długość wektora/norma wektora R^2
np.linalg.norm(v1)

4.123105625617661

In [10]:
#Norma euklidesowa R^n
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

In [11]:
#Odległość dwóch punktów na płaszczyźnie
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p - q)

5.0

In [12]:
#Odległość dwóch punktów w przestrzeni R^n
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p - q)

5.0990195135927845

In [16]:
#Mnożenie macierzy
X = np.array([[5,3], [3,9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [19]:
Z = np.dot(X,Y)
Z

array([[ 2],
       [-6]])

In [20]:
Z.shape

(2, 1)

In [23]:
X = np.array([[2,-1, 3], [3, 1, 0]])
Y = np.array([[2, 1, -1], [0, -1, 2], [3, 2, 0]])
print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [24]:
Z = np.dot(X, Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])

In [26]:
#Wyznacznik macierzy
A = np.array([[2,4], [-1,3]])
round(np.linalg.det(A))

10

In [27]:
#Ślad macierzy - suma przekątnej
A = np.array([[2,4], [-1,3]])
np.trace(A)

5

In [29]:
#Macierz jednostkowa - same 0, przekątna 1
np.eye(5,dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [34]:
#Macierz odwrotna
np.set_printoptions(precision=4, suppress=True)
A = np.array([[2,4], [-1,3]])
B = np.linalg.inv(A)
np.dot(A,B)


array([[1., 0.],
       [0., 1.]])

In [35]:
np.dot(B,A)

array([[ 1., -0.],
       [ 0.,  1.]])

In [36]:
#Macierz transponowana
A = np.array([[2,4], [-1,3]])
A.T

array([[ 2, -1],
       [ 4,  3]])

In [37]:
A = np.array([[2,1, -1], [0, -1, 2]])
A.T

array([[ 2,  0],
       [ 1, -1],
       [-1,  2]])

In [39]:
#Układ równań
# 2x+4y=10
# x-y=1
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [40]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [42]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

In [43]:
Z.shape

(2, 3)